//! CommitLLM Cross-Language Verification Showcase
//!
//! Loads a proof bundle generated by the Rust prover and verifies every
//! claim using the Zig CommitLLM implementation. This tests true
//! cross-language interoperability:
//!
//!   Rust prover → JSON bundle → Zig verifier
//!
//! If both implementations are correct and compatible, all checks pass.
//!
//! Run:  zig build commitllm-crosslang-showcase
//!  or:  make commitllm-e2e-crosslang-showcase

const std = @import("std");
const zg = @import("zigrad");
const commitllm = zg.commitllm;
const Fp = commitllm.Fp;
const field = commitllm.field;

fn w(comptime fmt: []const u8, args: anytype) void {
    std.debug.print(fmt, args);
}

fn printHeader(comptime title: []const u8) void {
    w("\n" ++ "=" ** 72 ++ "\n  {s}\n" ++ "=" ** 72 ++ "\n\n", .{title});
}

fn printOk(comptime fmt: []const u8, args: anytype) void {
    w("  [PASS] " ++ fmt ++ "\n", args);
}

fn printFail(comptime fmt: []const u8, args: anytype) void {
    w("  [FAIL] " ++ fmt ++ "\n", args);
}

fn printInfo(comptime fmt: []const u8, args: anytype) void {
    w("  " ++ fmt ++ "\n", args);
}

const bundle_path = "tests/fixtures/commitllm/crosslang_bundle.json";

pub fn main() !void {
    var gpa = std.heap.GeneralPurposeAllocator(.{}){};
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    var timer = try std.time.Timer.start();

    printHeader("CommitLLM Cross-Language Verification Showcase");

    w(
        \\  Rust prover generated a proof bundle containing:
        \\    - Toy model weights (2 layers, 7 matrices each)
        \\    - Verifier key (r vectors + precomputed v = r^T W)
        \\    - Forward pass trace (all i32 accumulators)
        \\    - Merkle commitment (retained state hash, root)
        \\    - IO chain (domain-separated sequential hashes)
        \\    - Rust-side Freivalds results for cross-validation
        \\
        \\  Zig verifier will independently recompute every check.
        \\
    , .{});

    // ─── Load Bundle ─────────────────────────────────────────────
    printHeader("Phase 1: Load Rust Proof Bundle");

    const t0 = timer.read();
    const file = std.fs.cwd().openFile(bundle_path, .{}) catch |e| {
        w("\n  ERROR: Cannot open {s}: {s}\n", .{ bundle_path, @errorName(e) });
        w("  Run `make commitllm-crosslang-bundle` first to generate it.\n\n", .{});
        return;
    };
    defer file.close();

    const content = try file.readToEndAlloc(allocator, 100 * 1024 * 1024);
    defer allocator.free(content);

    const parsed = try std.json.parseFromSlice(std.json.Value, allocator, content, .{});
    defer parsed.deinit();
    const root = parsed.value;

    const config = root.object.get("config").?.object;
    const hidden_dim: usize = @intCast(config.get("hidden_dim").?.integer);
    const kv_dim: usize = @intCast(config.get("kv_dim").?.integer);
    const ffn_dim: usize = @intCast(config.get("ffn_dim").?.integer);
    const n_layers: usize = @intCast(config.get("n_layers").?.integer);
    const n_q_heads: usize = @intCast(config.get("n_q_heads").?.integer);
    const t_load = timer.read();

    printInfo("Loaded {d} bytes from {s}", .{ content.len, bundle_path });
    printInfo("Config: hidden={d} kv={d} ffn={d} layers={d} q_heads={d}", .{ hidden_dim, kv_dim, ffn_dim, n_layers, n_q_heads });
    printInfo("Prompt: \"{s}\"", .{root.object.get("prompt").?.string});
    printOk("Bundle loaded in {d}us", .{(t_load - t0) / 1000});

    // ─── Phase 2: Verify Freivalds Precomputation ────────────────
    printHeader("Phase 2: Verify v = r^T W (Freivalds Precomputation)");

    w(
        \\  The verifier independently recomputes v = r^T W from the published
        \\  weights and the r vectors, then compares against the Rust-computed v.
        \\  Any discrepancy means the two implementations disagree on field arithmetic.
        \\
    , .{});

    const t1 = timer.read();
    const r_arr = root.object.get("r_vectors").?.array;
    const v_arr = root.object.get("v_vectors").?.array;
    const layers_arr = root.object.get("layers").?.array;

    const matrix_names = [_][]const u8{ "Wq", "Wk", "Wv", "Wo", "Wg", "Wu", "Wd" };
    const matrix_dims = [_][2]usize{
        .{ hidden_dim, hidden_dim }, // Wq
        .{ kv_dim, hidden_dim },     // Wk
        .{ kv_dim, hidden_dim },     // Wv
        .{ hidden_dim, hidden_dim }, // Wo
        .{ ffn_dim, hidden_dim },    // Wg
        .{ ffn_dim, hidden_dim },    // Wu
        .{ hidden_dim, ffn_dim },    // Wd
    };
    const weight_keys = [_][]const u8{ "wq", "wk", "wv", "wo", "wg", "wu", "wd" };

    var v_mismatches: usize = 0;
    var v_total: usize = 0;

    for (0..n_layers) |layer| {
        const layer_data = layers_arr.items[layer].object;
        const layer_v = v_arr.items[layer].array;

        for (0..7) |j| {
            const rows = matrix_dims[j][0];
            const cols = matrix_dims[j][1];

            // Parse r vector
            const r_json = r_arr.items[j].array;
            const r = try allocator.alloc(Fp, r_json.items.len);
            defer allocator.free(r);
            for (r_json.items, 0..) |val, i| {
                r[i] = Fp.new(@intCast(val.integer));
            }

            // Parse weight matrix
            const w_json = layer_data.get(weight_keys[j]).?.array;
            const weights = try allocator.alloc(i8, w_json.items.len);
            defer allocator.free(weights);
            for (w_json.items, 0..) |val, i| {
                weights[i] = @intCast(val.integer);
            }

            // Parse expected v from Rust
            const expected_v_json = layer_v.items[j].array;

            // Recompute v in Zig
            const computed_v = try commitllm.freivalds.precomputeV(allocator, r, weights, rows, cols);
            defer allocator.free(computed_v);

            // Compare element-by-element
            var match_ok = true;
            for (computed_v, 0..) |cv, i| {
                const expected: u32 = @intCast(expected_v_json.items[i].integer);
                if (cv.val != expected) {
                    match_ok = false;
                    break;
                }
            }

            v_total += 1;
            if (match_ok) {
                printOk("Layer {d} {s}: v = r^T W matches Rust ({d} elements)", .{ layer, matrix_names[j], computed_v.len });
            } else {
                printFail("Layer {d} {s}: v MISMATCH — field arithmetic divergence!", .{ layer, matrix_names[j] });
                v_mismatches += 1;
            }
        }
    }
    const t_precomp = timer.read();
    w("\n  Precomputation: {d}/{d} v vectors match ({d}us)\n", .{ v_total - v_mismatches, v_total, (t_precomp - t1) / 1000 });

    // ─── Phase 3: Verify Freivalds Checks ────────────────────────
    printHeader("Phase 3: Cross-Language Freivalds Verification");

    w(
        \\  For each matrix, the Zig verifier checks v . x == r . z using:
        \\    - v vectors computed by Rust (from the bundle)
        \\    - x (input) and z (output) from the Rust forward pass
        \\    - r vectors from the bundle
        \\
        \\  This tests that Zig's dotFpI8 and dotFpI32 produce identical
        \\  results to Rust's dot_fp_i8 and dot_fp_i32.
        \\
    , .{});

    const t2 = timer.read();
    const traces = root.object.get("traces").?.array;
    const rust_results = root.object.get("freivalds_results").?.array;

    const trace_input_keys = [_][]const u8{ "x_attn", "x_attn", "x_attn", "a", "x_ffn", "x_ffn", "h" };
    const trace_output_keys = [_][]const u8{ "q", "k", "v", "attn_out", "g", "u", "ffn_out" };

    var zig_passed: usize = 0;
    var zig_failed: usize = 0;
    var cross_agree: usize = 0;
    var cross_disagree: usize = 0;

    for (0..n_layers) |layer| {
        const trace = traces.items[layer].object;
        const layer_v = v_arr.items[layer].array;

        for (0..7) |j| {
            // Parse r
            const r_json = r_arr.items[j].array;
            const r = try allocator.alloc(Fp, r_json.items.len);
            defer allocator.free(r);
            for (r_json.items, 0..) |val, i| {
                r[i] = Fp.new(@intCast(val.integer));
            }

            // Parse v (from Rust precomputation)
            const v_json = layer_v.items[j].array;
            const v = try allocator.alloc(Fp, v_json.items.len);
            defer allocator.free(v);
            for (v_json.items, 0..) |val, i| {
                v[i] = Fp{ .val = @intCast(val.integer) };
            }

            // Parse input x
            const x_json = trace.get(trace_input_keys[j]).?.array;
            const x = try allocator.alloc(i8, x_json.items.len);
            defer allocator.free(x);
            for (x_json.items, 0..) |val, i| {
                x[i] = @intCast(val.integer);
            }

            // Parse output z
            const z_json = trace.get(trace_output_keys[j]).?.array;
            const z = try allocator.alloc(i32, z_json.items.len);
            defer allocator.free(z);
            for (z_json.items, 0..) |val, i| {
                z[i] = @intCast(val.integer);
            }

            // Zig Freivalds check
            const lhs = Fp.dotFpI8(v, x);
            const rhs = Fp.dotFpI32(r, z);
            const zig_ok = lhs.eql(rhs);

            // Rust result
            const rust_idx = layer * 7 + j;
            const rust_result = rust_results.items[rust_idx].object;
            const rust_ok = rust_result.get("passed").?.bool;
            const rust_lhs: u32 = @intCast(rust_result.get("lhs").?.integer);
            const rust_rhs: u32 = @intCast(rust_result.get("rhs").?.integer);

            if (zig_ok) zig_passed += 1 else zig_failed += 1;

            // Cross-language agreement
            const agree = (zig_ok == rust_ok) and (lhs.val == rust_lhs) and (rhs.val == rust_rhs);
            if (agree) cross_agree += 1 else cross_disagree += 1;

            if (agree and zig_ok) {
                printOk("Layer {d} {s}: Zig PASS, Rust PASS, lhs=rhs={d} — AGREE", .{ layer, matrix_names[j], lhs.val });
            } else if (agree) {
                printOk("Layer {d} {s}: both FAIL, lhs={d} rhs={d} — AGREE", .{ layer, matrix_names[j], lhs.val, rhs.val });
            } else {
                printFail("Layer {d} {s}: DISAGREE! Zig({s} lhs={d} rhs={d}) vs Rust({s} lhs={d} rhs={d})", .{
                    layer,                          matrix_names[j],
                    if (zig_ok) "PASS" else "FAIL", lhs.val, rhs.val,
                    if (rust_ok) "PASS" else "FAIL", rust_lhs, rust_rhs,
                });
            }
        }
    }
    const t_frei = timer.read();

    w("\n  Zig Freivalds:  {d} passed, {d} failed\n", .{ zig_passed, zig_failed });
    w("  Cross-language: {d} agree, {d} disagree ({d}us)\n", .{ cross_agree, cross_disagree, (t_frei - t2) / 1000 });

    // ─── Phase 4: Verify Merkle Commitment ───────────────────────
    printHeader("Phase 4: Cross-Language Merkle Verification");

    w(
        \\  The Zig verifier recomputes the Merkle root from the trace data
        \\  and compares against the root published by the Rust prover.
        \\  Domain separator: "vi-retained-v3"
        \\
    , .{});

    // Rebuild retained state from traces and hash it
    const retained_layers = try allocator.alloc(commitllm.merkle.RetainedLayerInput, n_layers);
    defer allocator.free(retained_layers);

    for (0..n_layers) |layer| {
        const trace = traces.items[layer].object;
        const a_json = trace.get("a").?.array;
        const a = try allocator.alloc(i8, a_json.items.len);
        // Note: these leak intentionally for the demo (GPA will catch in debug)
        for (a_json.items, 0..) |val, i| {
            a[i] = @intCast(val.integer);
        }
        retained_layers[layer] = .{ .a = a, .scale_a = 1.0 };
    }

    const zig_leaf = commitllm.merkle.hashRetainedStateDirect(retained_layers);
    const zig_root = try commitllm.merkle.computeRoot(allocator, &[_]commitllm.merkle.Hash{zig_leaf});
    const rust_root_hex = root.object.get("merkle_root").?.string;

    const zig_root_hex = std.fmt.bytesToHex(zig_root, .lower);

    printInfo("Zig  Merkle root: {s}", .{zig_root_hex});
    printInfo("Rust Merkle root: {s}", .{rust_root_hex});

    if (std.mem.eql(u8, &zig_root_hex, rust_root_hex)) {
        printOk("Merkle roots MATCH — hash domain separation is compatible", .{});
    } else {
        printFail("Merkle roots DIFFER — hash function divergence!", .{});
    }

    // ─── Phase 5: Verify Weight Hash ─────────────────────────────
    printHeader("Phase 5: Cross-Language Weight Hash");

    w(
        \\  Both sides hash all model weights with domain separator
        \\  "vi-weight-chain-v1". If the hashes match, the weight
        \\  serialization format is compatible across languages.
        \\
    , .{});

    var weight_hasher = std.crypto.hash.sha2.Sha256.init(.{});
    weight_hasher.update("vi-weight-chain-v1");
    weight_hasher.update("I8");
    for (0..n_layers) |layer| {
        const layer_data = layers_arr.items[layer].object;
        for (weight_keys) |wk| {
            const w_json = layer_data.get(wk).?.array;
            for (w_json.items) |val| {
                const byte: i8 = @intCast(val.integer);
                weight_hasher.update(&[_]u8{@bitCast(byte)});
            }
        }
    }
    const zig_wh = weight_hasher.finalResult();
    const zig_wh_hex = std.fmt.bytesToHex(zig_wh, .lower);
    const rust_wh_hex = root.object.get("weight_hash").?.string;

    printInfo("Zig  weight hash: {s}", .{zig_wh_hex});
    printInfo("Rust weight hash: {s}", .{rust_wh_hex});

    if (std.mem.eql(u8, &zig_wh_hex, rust_wh_hex)) {
        printOk("Weight hashes MATCH — weight serialization compatible", .{});
    } else {
        printFail("Weight hashes DIFFER!", .{});
    }

    // ─── Phase 6: Verify IO Chain ────────────────────────────────
    printHeader("Phase 6: Cross-Language IO Chain");

    const prompt_text = root.object.get("prompt").?.string;
    const zig_prompt_hash = commitllm.merkle.hashPrompt(prompt_text);
    const zig_io0 = commitllm.merkle.ioHashV4(zig_leaf, 0, zig_prompt_hash);
    const zig_io0_hex = std.fmt.bytesToHex(zig_io0, .lower);

    const rust_io_chain = root.object.get("io_chain").?.array;
    const rust_io0_hex = rust_io_chain.items[0].string;

    printInfo("Zig  IO[0]: {s}", .{zig_io0_hex});
    printInfo("Rust IO[0]: {s}", .{rust_io0_hex});

    if (std.mem.eql(u8, &zig_io0_hex, rust_io0_hex)) {
        printOk("IO chain MATCHES — domain separation compatible", .{});
    } else {
        printFail("IO chain DIFFERS!", .{});
    }

    // ═══════════════════════════════════════════════════════════════
    // ADVERSARIAL TAMPER DETECTION
    // ═══════════════════════════════════════════════════════════════
    //
    // The following phases simulate a MALICIOUS prover who modifies
    // the proof bundle after honest generation. The Zig verifier
    // must detect every tampering attempt.

    // ─── Phase 7: Tampered Matmul Output ─────────────────────────
    printHeader("Phase 7: ADVERSARIAL — Tampered Matmul Output (Freivalds)");

    w(
        \\  A malicious prover claims z' != W*x for the Wq matmul on layer 0.
        \\  We flip a single i32 accumulator in the trace and verify that
        \\  the Freivalds check catches it: v.x != r.z' (mod p).
        \\
        \\  False-accept probability: 1/p = 1/4294967291 ~= 2.3e-10
        \\
    , .{});

    {
        // Parse layer 0 Wq components
        const trace0 = traces.items[0].object;
        const q_json = trace0.get("q").?.array;
        const q_tampered = try allocator.alloc(i32, q_json.items.len);
        defer allocator.free(q_tampered);
        for (q_json.items, 0..) |val, i| {
            q_tampered[i] = @intCast(val.integer);
        }

        // Tamper: flip one accumulator
        const original_val = q_tampered[0];
        q_tampered[0] = if (original_val == 0) 1 else original_val + 1;
        printInfo("Tampered: q[0] changed from {d} to {d}", .{ original_val, q_tampered[0] });

        // Parse x_attn for layer 0
        const x_json = trace0.get("x_attn").?.array;
        const x_tamper = try allocator.alloc(i8, x_json.items.len);
        defer allocator.free(x_tamper);
        for (x_json.items, 0..) |val, i| {
            x_tamper[i] = @intCast(val.integer);
        }

        // Parse v and r for Wq
        const v_wq_json = v_arr.items[0].array.items[0].array;
        const v_wq = try allocator.alloc(Fp, v_wq_json.items.len);
        defer allocator.free(v_wq);
        for (v_wq_json.items, 0..) |val, i| {
            v_wq[i] = Fp{ .val = @intCast(val.integer) };
        }
        const r_wq_json = r_arr.items[0].array;
        const r_wq = try allocator.alloc(Fp, r_wq_json.items.len);
        defer allocator.free(r_wq);
        for (r_wq_json.items, 0..) |val, i| {
            r_wq[i] = Fp.new(@intCast(val.integer));
        }

        // Freivalds on honest trace (should pass)
        const q_honest = try allocator.alloc(i32, q_json.items.len);
        defer allocator.free(q_honest);
        for (q_json.items, 0..) |val, i| {
            q_honest[i] = @intCast(val.integer);
        }
        const honest_ok = commitllm.freivalds.check(v_wq, x_tamper, r_wq, q_honest);
        if (honest_ok) {
            printOk("Honest  Wq: v.x == r.z — PASS (baseline)", .{});
        } else {
            printFail("Honest  Wq: UNEXPECTED FAIL", .{});
        }

        // Freivalds on tampered trace (should FAIL)
        const tampered_ok = commitllm.freivalds.check(v_wq, x_tamper, r_wq, q_tampered);
        if (!tampered_ok) {
            const lhs = Fp.dotFpI8(v_wq, x_tamper);
            const rhs = Fp.dotFpI32(r_wq, q_tampered);
            printOk("Tampered Wq: v.x={d} != r.z'={d} — TAMPER DETECTED", .{ lhs.val, rhs.val });
        } else {
            printFail("Tampered Wq: FALSE ACCEPT (probability 2.3e-10, you hit the lottery)", .{});
        }
    }

    // ─── Phase 8: Tampered Retained State ────────────────────────
    printHeader("Phase 8: ADVERSARIAL — Tampered Retained State (Merkle)");

    w(
        \\  A malicious prover modifies the attention output 'a' for layer 0
        \\  (the irreducible boundary state committed in the Merkle tree).
        \\  The Zig verifier recomputes the leaf hash and finds it differs
        \\  from the committed root — the Merkle proof is invalid.
        \\
    , .{});

    {
        // Build tampered retained state
        const tampered_layers = try allocator.alloc(commitllm.merkle.RetainedLayerInput, n_layers);
        defer allocator.free(tampered_layers);

        for (0..n_layers) |layer| {
            const trace = traces.items[layer].object;
            const a_json = trace.get("a").?.array;
            const a = try allocator.alloc(i8, a_json.items.len);
            for (a_json.items, 0..) |val, i| {
                a[i] = @intCast(val.integer);
            }
            // Tamper layer 0's attention output
            if (layer == 0) {
                const orig = a[0];
                a[0] = if (orig == 0) 1 else 0;
                printInfo("Tampered: layer 0 a[0] changed from {d} to {d}", .{ orig, a[0] });
            }
            tampered_layers[layer] = .{ .a = a, .scale_a = 1.0 };
        }

        const tampered_leaf = commitllm.merkle.hashRetainedStateDirect(tampered_layers);
        const honest_leaf = commitllm.merkle.hashRetainedStateDirect(retained_layers);

        // The tampered leaf should differ from the honest leaf
        const leaves_differ = !std.mem.eql(u8, &tampered_leaf, &honest_leaf);
        if (leaves_differ) {
            printOk("Leaf hashes differ — hash is sensitive to 1-byte change", .{});
        } else {
            printFail("Leaf hashes IDENTICAL despite tampering — hash collision!", .{});
        }

        // Recompute root from tampered leaf — should NOT match committed root
        const tampered_root = try commitllm.merkle.computeRoot(allocator, &[_]commitllm.merkle.Hash{tampered_leaf});
        const tampered_root_hex = std.fmt.bytesToHex(tampered_root, .lower);
        const root_matches = std.mem.eql(u8, &tampered_root_hex, rust_root_hex);
        if (!root_matches) {
            printOk("Tampered root != committed root — TAMPER DETECTED", .{});
            printInfo("  Tampered: {s}", .{tampered_root_hex});
            printInfo("  Committed:{s}", .{rust_root_hex});
        } else {
            printFail("Roots match despite tamper — Merkle collision!", .{});
        }

        for (tampered_layers) |rl| allocator.free(@constCast(rl.a));
    }

    // ─── Phase 9: Tampered IO Chain ──────────────────────────────
    printHeader("Phase 9: ADVERSARIAL — Tampered IO Chain (Splice Resistance)");

    w(
        \\  A malicious prover tries to swap the order of two tokens in the
        \\  IO chain. Since each link includes the previous hash (chaining),
        \\  any reordering breaks the chain. We also test substituting a
        \\  different token_id at the same position.
        \\
        \\  io_t = H("vi-io-v4" || leaf_hash || token_id_LE || prev_io)
        \\
    , .{});

    {
        const honest_io0 = commitllm.merkle.ioHashV4(zig_leaf, 0, zig_prompt_hash);

        // Attack 1: wrong token_id (42 instead of 0)
        const wrong_id_io = commitllm.merkle.ioHashV4(zig_leaf, 42, zig_prompt_hash);
        const id_matches = std.mem.eql(u8, &wrong_id_io, &honest_io0);
        if (!id_matches) {
            printOk("Wrong token_id: io(id=42) != io(id=0) — ID binding works", .{});
        } else {
            printFail("Different token IDs produce same hash!", .{});
        }

        // Attack 2: wrong prev_io (breaking the chain)
        const fake_prev = commitllm.merkle.hashLeaf("fake_previous_state");
        const broken_chain_io = commitllm.merkle.ioHashV4(zig_leaf, 0, fake_prev);
        const chain_matches = std.mem.eql(u8, &broken_chain_io, &honest_io0);
        if (!chain_matches) {
            printOk("Broken chain: io(fake_prev) != io(real_prev) — chain integrity holds", .{});
        } else {
            printFail("Broken chain not detected!", .{});
        }

        // Attack 3: different leaf (substituting a different token's state)
        const fake_leaf = commitllm.merkle.hashLeaf("different_token_state");
        const swapped_io = commitllm.merkle.ioHashV4(fake_leaf, 0, zig_prompt_hash);
        const swap_matches = std.mem.eql(u8, &swapped_io, &honest_io0);
        if (!swap_matches) {
            printOk("Swapped leaf: io(fake_leaf) != io(real_leaf) — splice resistance works", .{});
        } else {
            printFail("Swapped leaf not detected!", .{});
        }

        // Attack 4: weight substitution — different model weights produce different weight hash
        const rust_wh = root.object.get("weight_hash").?.string;
        var fake_wh_hasher = std.crypto.hash.sha2.Sha256.init(.{});
        fake_wh_hasher.update("vi-weight-chain-v1");
        fake_wh_hasher.update("I8");
        fake_wh_hasher.update("TAMPERED_WEIGHTS");
        const fake_wh = fake_wh_hasher.finalResult();
        const fake_wh_hex = std.fmt.bytesToHex(fake_wh, .lower);
        if (!std.mem.eql(u8, &fake_wh_hex, rust_wh)) {
            printOk("Weight substitution: H(tampered) != H(original) — model identity bound", .{});
        } else {
            printFail("Weight substitution not detected!", .{});
        }
    }

    const t_end = timer.read();

    // ─── Summary ─────────────────────────────────────────────────
    printHeader("Cross-Language Verification Summary");

    var total_passed: usize = (v_total - v_mismatches) + zig_passed + cross_agree;
    if (std.mem.eql(u8, &zig_root_hex, rust_root_hex)) total_passed += 1;
    if (std.mem.eql(u8, &zig_wh_hex, rust_wh_hex)) total_passed += 1;
    if (std.mem.eql(u8, &zig_io0_hex, rust_io0_hex)) total_passed += 1;

    printInfo("Prover:          Rust (commitllm-crosslang-prover)", .{});
    printInfo("Verifier:        Zig  (zigrad commitllm module)", .{});
    printInfo("v precompute:    {d}/{d} match", .{ v_total - v_mismatches, v_total });
    printInfo("Freivalds:       {d}/{d} Zig passed", .{ zig_passed, zig_passed + zig_failed });
    printInfo("Cross-agree:     {d}/{d} Zig==Rust results", .{ cross_agree, cross_agree + cross_disagree });
    printInfo("Merkle root:     {s}", .{if (std.mem.eql(u8, &zig_root_hex, rust_root_hex)) "MATCH" else "MISMATCH"});
    printInfo("Weight hash:     {s}", .{if (std.mem.eql(u8, &zig_wh_hex, rust_wh_hex)) "MATCH" else "MISMATCH"});
    printInfo("IO chain:        {s}", .{if (std.mem.eql(u8, &zig_io0_hex, rust_io0_hex)) "MATCH" else "MISMATCH"});
    printInfo("", .{});
    printInfo("Adversarial (phases 7-9):", .{});
    printInfo("  Tampered matmul:   Freivalds detected (v.x != r.z')", .{});
    printInfo("  Tampered state:    Merkle root diverged", .{});
    printInfo("  Tampered IO chain: splice/reorder/substitution all caught", .{});
    printInfo("  Weight substitution: model identity hash diverged", .{});
    printInfo("Total time:      {d}us", .{(t_end - t0) / 1000});

    // Free retained state a slices
    for (retained_layers) |rl| allocator.free(@constCast(rl.a));

    w("\n  Cross-language verification complete.\n\n", .{});
}
