pub const HostDevice = @import("device/host_device.zig");
pub const CudaDevice = @import("device/cuda_device.zig");
pub const DeviceReference = @import("device/device_reference.zig");
const host_blas = @import("device/host_blas_provider.zig");
pub const ReduceType = @import("device/device_common.zig").ReduceType;
pub const SmaxType = @import("device/device_common.zig").SmaxType;
pub const RandType = @import("device/device_common.zig").RandType;
pub const HostBlasProvider = host_blas.HostBlasProvider;
pub const HostOpTelemetry = HostDevice.HostOpTelemetry;
pub const configured_host_blas_provider = host_blas.configured_host_blas_provider;
pub const configured_host_backend = host_blas.configured_host_backend;
pub const using_mkl = configured_host_blas_provider == .mkl;
pub const opspec = @import("device/opspec.zig");
pub const Error = @import("allocators.zig").Error;
pub const DeviceData = @import("allocators.zig").DeviceData;
